# Generated by Django 5.1.3 on 2024-12-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarGenerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start', models.DateTimeField()),
                ('generated_energy', models.FloatField(help_text='Energy generated in kWh')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_data', to='locations.location')),
            ],
            options={
                'verbose_name': 'Solar Generation Data',
                'verbose_name_plural': 'Solar Generation Data',
                'ordering': ['interval_start'],
            },
        ),
    ]

