# Generated by Django 5.1.3 on 2024-12-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_solargenerationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('relative_humidity', models.IntegerField()),
                ('cloud_coverage', models.IntegerField()),
                ('radiation_w_m2', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='locations.location')),
            ],
        ),
    ]

